- name: Create DNS aliases
  dnsalias:
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ dns_alias | default([]) }}"
  notify: update config"
