- name: Configure tunnel server
  tunnelserver:
    dnsname: "{{ tunnel_server.dns_name }}"
    network: "{{ tunnel_server.network }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment | default('') }}"
    enable: "{{ item.enable | default(true) }}"
    index: "{{ idx }}"
  loop: "{{ tunnel_server.tunnels }}"
  loop_control:
    index_var: idx
  notify: update tunnels
  when: tunnel_server is defined

- name: Configure tunnel clients
  tunnelclient:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    network: "{{ item.network }}"
    comment: "{{ item.comment | default('') }}"
    state: "{{ item.state | default('present') }}"
    enable: "{{ item.enable | default(true) }}"
  loop: "{{ tunnel_clients }}"
  notify: update tunnels
  when: tunnel_clients is defined
