- include_role:
    name: base
  when: kn6plv_aredn_base_loaded is not defined

- name: Advanced configuration
  advconfig:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ advanced | default([]) }}"
  notify: need reboot
