- name: Setup node basics
  basics:
    description: "{{ description | default(omit) }}"
    lat_lon: "{{ location | default(omit) }}"
    timezone: "{{ timezone | default(omit) }}"
    ntp_server: "{{ ntp_server | default(omit) }}"
  notify: 
    - update basic config
    - need reboot

- name: Setup MESH
  meshrf:
    enable: "{{ mesh.enable | default(omit) }}"
    address: "{{ mesh.address | default(omit) }}"
    ssid: "{{ mesh.ssid | default(omit) }}"
    channel: "{{ mesh.channel | default(omit) }}"
    channel_width: "{{ mesh.channel_width | default(omit) }}"
    tx_power: "{{ mesh.tx_power | default(omit) }}"
    distance: "{{ mesh.distance | default(omit)}}"
  notify:
    - update basic config
    - need reboot
  when: mesh is defined

- name: Setup LAN
  lan:
    dhcp_enable: "{{ dhcp.enable | default(omit) }}"
    hosts: "{{ dhcp.hosts | default(omit) }}"
    address: "{{ dhcp.address | default(omit) }}"
    netmask: "{{ dhcp.netmask | default(omit) }}"
    dhcp_start: "{{ dhcp.start | default(omit) }}"
    dhcp_end: "{{ dhcp.end | default(omit) }}"
  notify:
    - update basic config
    - need reboot
  when: dhcp is defined

- name: Setup WAN
  wan:
    enable: "{{ wan.enable | default(omit) }}"
    protocol: "{{ wan.protocol | default(omit) }}"
    address: "{{ wan.address | default(omit) }}"
    netmask: "{{ wan.netmask | default(omit) }}"
    gateway: "{{ wan.gateway | default(omit) }}"
    dns: "{{ wan.dns | default(omit) }}"
    allow_mesh: "{{ wan.allow_mesh | default(omit) }}"
    allow_lan: "{{ wan.allow_lan | default(omit) }}"
  notify:
    - update basic config
    - need reboot
  when: wan is defined
