# Install meshchat on a node

- name: Advertise meshchat
  advertise:
    name: "{{ meshchatname }}"
    path: "meshchat"
    state: present
  notify: "update config"

- name: Download latest meshchat package
  get_url:
    url: "{{ meshchaturl }}"
    dest: /tmp
  delegate_to: 127.0.0.1
  run_once: true

- name: Copy packages to node
  copy:
    src: "/tmp/{{ meshchaturl | basename }}"
    dest: "/root/{{ meshchaturl | basename }}"
  register: packagescopy

- name: Install packages
  opkg:
    name: "{{ meshchaturl | basename }}"
    pkg: "/root/{{ meshchaturl | basename }}"
    state: present
    update_cache: true
    cache_valid_time: 3600,
    reinstall: "{{ packagescopy.changed }}"
  notify: "update config"
