- name: Forward ports
  portforward:
    interface: "{{ item.interface }}"
    type: "{{ item.type | default(both) }}"
    port: "{{ item.port }}"
    address: "{{ item.address | default('localhost') }}"
    lanport: "{{ item.lanport | item.port }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ port_forward | default([]) }}"
  notify: update config
